language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gleison/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gleison/react-test npm test

after_success:
  - docker build -t gleisonbs/multi-client ./client
  - docker build -t gleisonbs/multi-nginx ./nginx
  - docker build -t gleisonbs/multi-server ./server
  - docker build -t gleisonbs/multi-worker ./worker

  - echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_USERNAME --password-stdin

  - docker push gleisonbs/multi-client
  - docker push gleisonbs/multi-nginx
  - docker push gleisonbs/multi-server
  - docker push gleisonbs/multi-worker